/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package texteditor;

import java.awt.Color;
import java.awt.Font;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

import java.awt.font.TextAttribute;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;

import java.io.File;
import javax.swing.filechooser.FileFilter;

import javax.swing.filechooser.FileNameExtensionFilter;


import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import javax.swing.text.StyledDocument;


/**
 *
 * @author Nisrat
 */
public class TextEditorFrame extends javax.swing.JFrame implements ActionListener{

    private Object FontName;
    private StyledDocument styledDocument;
     public TextEditorFrame() throws BadLocationException {
          initComponents();
        this.styledDocument = new DefaultStyledDocument();
        this.styledDocument.insertString(0, textArea.getText(), null);
        addStylesToDocument(styledDocument);
    }

     private void addStylesToDocument(StyledDocument styledDocument) {
        Style def = StyleContext.getDefaultStyleContext().getStyle(
                StyleContext.DEFAULT_STYLE);
        Style s = styledDocument.addStyle("bold", def);
        StyleConstants.setBold(s, true);
    }

    //public TextEditorFrame() {
       
       // initComponents();
        //addMouseListener(this);
        // addMouseMotionListener(this);
        
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        newButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        statusField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        copyButton = new javax.swing.JButton();
        pasteButton = new javax.swing.JButton();
        Bold1 = new javax.swing.JButton();
        Italic = new javax.swing.JButton();
        cut = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        Asize12 = new javax.swing.JMenuItem();
        Asize16 = new javax.swing.JMenuItem();
        Asize20 = new javax.swing.JMenuItem();
        Asize24 = new javax.swing.JMenuItem();
        Asize36 = new javax.swing.JMenuItem();
        Asize40 = new javax.swing.JMenuItem();
        Asize48 = new javax.swing.JMenuItem();
        Asize54 = new javax.swing.JMenuItem();
        Asize60 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        fs1 = new javax.swing.JMenuItem();
        fs2 = new javax.swing.JMenuItem();
        fs3 = new javax.swing.JMenuItem();
        fs4 = new javax.swing.JMenuItem();
        fs5 = new javax.swing.JMenuItem();
        fs6 = new javax.swing.JMenuItem();
        fs7 = new javax.swing.JMenuItem();
        fs8 = new javax.swing.JMenuItem();
        fs9 = new javax.swing.JMenuItem();
        fs10 = new javax.swing.JMenuItem();
        fs11 = new javax.swing.JMenuItem();
        fs13 = new javax.swing.JMenuItem();
        fa14 = new javax.swing.JMenuItem();
        fs15 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        red = new javax.swing.JMenuItem();
        blue = new javax.swing.JMenuItem();
        black = new javax.swing.JMenuItem();
        yellow = new javax.swing.JMenuItem();
        green = new javax.swing.JMenuItem();
        orange = new javax.swing.JMenuItem();
        pink = new javax.swing.JMenuItem();
        magenta = new javax.swing.JMenuItem();
        cyan = new javax.swing.JMenuItem();
        gray = new javax.swing.JMenuItem();
        darkgray = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem2.setText("jMenuItem2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem15.setText("jMenuItem15");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newButton.setText("New");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save As");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        statusField.setEditable(false);

        textArea.setColumns(20);
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textArea);

        copyButton.setText("Copy");
        copyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyButtonActionPerformed(evt);
            }
        });

        pasteButton.setText("Paste");
        pasteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteButtonActionPerformed(evt);
            }
        });

        Bold1.setText("Bold");
        Bold1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bold1ActionPerformed(evt);
            }
        });

        Italic.setText("Italic");
        Italic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItalicActionPerformed(evt);
            }
        });

        cut.setText("Cut");
        cut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutActionPerformed(evt);
            }
        });

        jMenu2.setText("Size");

        Asize12.setText("12");
        Asize12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Asize12ActionPerformed(evt);
            }
        });
        jMenu2.add(Asize12);

        Asize16.setText("16");
        Asize16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Asize16ActionPerformed(evt);
            }
        });
        jMenu2.add(Asize16);

        Asize20.setText("20");
        Asize20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Asize20ActionPerformed(evt);
            }
        });
        jMenu2.add(Asize20);

        Asize24.setText("24");
        Asize24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Asize24ActionPerformed(evt);
            }
        });
        jMenu2.add(Asize24);

        Asize36.setText("36");
        Asize36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Asize36ActionPerformed(evt);
            }
        });
        jMenu2.add(Asize36);

        Asize40.setText("40");
        Asize40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Asize40ActionPerformed(evt);
            }
        });
        jMenu2.add(Asize40);

        Asize48.setText("48");
        Asize48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Asize48ActionPerformed(evt);
            }
        });
        jMenu2.add(Asize48);

        Asize54.setText("54");
        Asize54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Asize54ActionPerformed(evt);
            }
        });
        jMenu2.add(Asize54);

        Asize60.setText("60");
        Asize60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Asize60ActionPerformed(evt);
            }
        });
        jMenu2.add(Asize60);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Font");

        fs1.setText("Arial");
        fs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fs1ActionPerformed(evt);
            }
        });
        jMenu1.add(fs1);

        fs2.setText("Arial Black");
        fs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fs2ActionPerformed(evt);
            }
        });
        jMenu1.add(fs2);

        fs3.setText("Arial Narrow");
        fs3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fs3ActionPerformed(evt);
            }
        });
        jMenu1.add(fs3);

        fs4.setText("Berlin Sans FB Demi");
        fs4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fs4ActionPerformed(evt);
            }
        });
        jMenu1.add(fs4);

        fs5.setText("Bernard MT Condensed");
        fs5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fs5ActionPerformed(evt);
            }
        });
        jMenu1.add(fs5);

        fs6.setText("Britannic Bold");
        fs6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fs6ActionPerformed(evt);
            }
        });
        jMenu1.add(fs6);

        fs7.setText("Brush Script MT");
        fs7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fs7ActionPerformed(evt);
            }
        });
        jMenu1.add(fs7);

        fs8.setText("Broadway");
        fs8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fs8ActionPerformed(evt);
            }
        });
        jMenu1.add(fs8);

        fs9.setText("Copper Black");
        fs9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fs9ActionPerformed(evt);
            }
        });
        jMenu1.add(fs9);

        fs10.setText("Eras Bold ITC");
        fs10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fs10ActionPerformed(evt);
            }
        });
        jMenu1.add(fs10);

        fs11.setText("Harlow Solid Italic");
        fs11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fs11ActionPerformed(evt);
            }
        });
        jMenu1.add(fs11);

        fs13.setText("Times New Roman");
        fs13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fs13ActionPerformed(evt);
            }
        });
        jMenu1.add(fs13);

        fa14.setText("Verdana");
        fa14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fa14ActionPerformed(evt);
            }
        });
        jMenu1.add(fa14);

        fs15.setText("Yu Mincho Demibold");
        fs15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fs15ActionPerformed(evt);
            }
        });
        jMenu1.add(fs15);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Color");

        red.setText("Red");
        red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redActionPerformed(evt);
            }
        });
        jMenu5.add(red);

        blue.setText("Blue");
        blue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueActionPerformed(evt);
            }
        });
        jMenu5.add(blue);

        black.setText("Black");
        black.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackActionPerformed(evt);
            }
        });
        jMenu5.add(black);

        yellow.setText("Yellow");
        yellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowActionPerformed(evt);
            }
        });
        jMenu5.add(yellow);

        green.setText("Green");
        green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenActionPerformed(evt);
            }
        });
        jMenu5.add(green);

        orange.setText("Orange");
        orange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeActionPerformed(evt);
            }
        });
        jMenu5.add(orange);

        pink.setText("Pink");
        pink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinkActionPerformed(evt);
            }
        });
        jMenu5.add(pink);

        magenta.setText("Magenta");
        magenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                magentaActionPerformed(evt);
            }
        });
        jMenu5.add(magenta);

        cyan.setText("Cyan");
        cyan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cyanActionPerformed(evt);
            }
        });
        jMenu5.add(cyan);

        gray.setText("Gray");
        gray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grayActionPerformed(evt);
            }
        });
        jMenu5.add(gray);

        darkgray.setText("Dark-Gray");
        darkgray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkgrayActionPerformed(evt);
            }
        });
        jMenu5.add(darkgray);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Bold1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newButton, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Italic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cut, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(copyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pasteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusField, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newButton)
                    .addComponent(saveButton)
                    .addComponent(loadButton)
                    .addComponent(quitButton)
                    .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(copyButton)
                    .addComponent(pasteButton)
                    .addComponent(cut))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bold1)
                    .addComponent(Italic))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        textArea.setText("");
        statusField.setText("New file.");
    }//GEN-LAST:event_newButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
       System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
         JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Text Documents","txt"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("PDF Documents", "pdf"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("MS Office Documents", "docx", "xlsx", "pptx"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("CSV", "csv"));
         
        fileChooser.setAcceptAllFileFilterUsed(true);
        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
              try {
                String fileName = fileChooser.getSelectedFile().getName();
                PrintWriter fout=new PrintWriter(fileChooser.getSelectedFile());
                
                if(fileName.contains(".txt")){
                   
               }
               if(fileName.contains(".doc")){
                fileName = fileName + ".doc";    
               }
                if(fileName.contains(".pdf")){
                fileName = fileName + ".pdf";    
               }
                
               if(fileName.contains(".csv")){
                fileName = fileName + ".csv";    
               }
               else{
                   fileName = fileName + ".txt";    
               }

                fout.print(textArea.getText());
                fout.close();
                statusField.setText("Saved"+ fileChooser.getSelectedFile().getAbsolutePath());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(TextEditorFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
            //File selectedFile = fileChooser.getSelectedFile();
            //System.out.println("Selected file: " + selectedFile.getAbsolutePath());
        
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
         JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("PDF Documents", "pdf"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("MS Office Documents", "docx", "xlsx", "pptx"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Text Documents", "txt"));
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("CSV", "csv"));
        fileChooser.setAcceptAllFileFilterUsed(true);
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
           try {
                    Scanner fin =new Scanner(fileChooser.getSelectedFile());
                     String buffer="";
                     while(fin.hasNext()){
                
                        buffer += fin.nextLine()+"\n";
                    }
                    textArea.setText(buffer);
                    fin.close();
                    statusField.setText("Loaded"+ fileChooser.getSelectedFile().getAbsolutePath());
                } catch (FileNotFoundException ex) {
                     JOptionPane.showMessageDialog(this,"File Not Found");
                }
        }
                   
               
    }//GEN-LAST:event_loadButtonActionPerformed

    private void copyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyButtonActionPerformed
        textArea.copy();
    }//GEN-LAST:event_copyButtonActionPerformed

    private void pasteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteButtonActionPerformed
        textArea.paste();
    }//GEN-LAST:event_pasteButtonActionPerformed

    private void Bold1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bold1ActionPerformed
        // TODO add your handling code here:
               
      //textArea.addCaretListener(new SelectedText());
    //String s=textArea.getSelectedText();
       // textArea.setText(s);
    
      textArea.setFont(new Font(textArea.getFont().getFamily(),Font.BOLD,textArea.getFont().getSize()));
        
    }//GEN-LAST:event_Bold1ActionPerformed
          
                

    private void ItalicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItalicActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font(textArea.getFont().getFamily(),Font.ITALIC,textArea.getFont().getSize()));
    }//GEN-LAST:event_ItalicActionPerformed
     
    private void Asize12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Asize12ActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font(textArea.getFont().getFamily(),Font.PLAIN,12));
        
        
    }//GEN-LAST:event_Asize12ActionPerformed

    private void Asize16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Asize16ActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font(textArea.getFont().getFamily(),Font.PLAIN,16));
    }//GEN-LAST:event_Asize16ActionPerformed

    private void Asize20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Asize20ActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font(textArea.getFont().getFamily(),Font.PLAIN,20));
    }//GEN-LAST:event_Asize20ActionPerformed

    private void Asize24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Asize24ActionPerformed
        // TODO add your handling code here:
         textArea.setFont(new Font(textArea.getFont().getFamily(),Font.PLAIN,24));
    }//GEN-LAST:event_Asize24ActionPerformed

    private void Asize36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Asize36ActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font(textArea.getFont().getFamily(),Font.PLAIN,36));
    }//GEN-LAST:event_Asize36ActionPerformed

    private void Asize40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Asize40ActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font(textArea.getFont().getFamily(),Font.PLAIN,40));
    }//GEN-LAST:event_Asize40ActionPerformed

    private void Asize48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Asize48ActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font(textArea.getFont().getFamily(),Font.PLAIN,48));
    }//GEN-LAST:event_Asize48ActionPerformed

    private void Asize54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Asize54ActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font(textArea.getFont().getFamily(),Font.PLAIN,54));
    }//GEN-LAST:event_Asize54ActionPerformed

    private void Asize60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Asize60ActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font(textArea.getFont().getFamily(),Font.PLAIN,60));
    }//GEN-LAST:event_Asize60ActionPerformed

    private void fs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fs1ActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font("Arial",Font.PLAIN,textArea.getFont().getSize()));
    }//GEN-LAST:event_fs1ActionPerformed

    private void fs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fs2ActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font("Arial Black",Font.PLAIN,textArea.getFont().getSize()));
    }//GEN-LAST:event_fs2ActionPerformed

    private void fs3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fs3ActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font("Arial Narrow",Font.PLAIN,textArea.getFont().getSize()));
    }//GEN-LAST:event_fs3ActionPerformed

    private void fs4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fs4ActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font("Berlin Sans FB Demi",Font.PLAIN,textArea.getFont().getSize()));
    }//GEN-LAST:event_fs4ActionPerformed

    private void fs5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fs5ActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font("Bernard MT Condensed",Font.PLAIN,textArea.getFont().getSize()));
    }//GEN-LAST:event_fs5ActionPerformed

    private void fs6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fs6ActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font("Britannic Bold",Font.PLAIN,textArea.getFont().getSize()));
    }//GEN-LAST:event_fs6ActionPerformed

    private void fs7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fs7ActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font("Brush Script MT",Font.PLAIN,textArea.getFont().getSize()));
    }//GEN-LAST:event_fs7ActionPerformed

    private void fs8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fs8ActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font("Broadway",Font.PLAIN,textArea.getFont().getSize()));
    }//GEN-LAST:event_fs8ActionPerformed

    private void fs9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fs9ActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font("Copper Black",Font.PLAIN,textArea.getFont().getSize()));
    }//GEN-LAST:event_fs9ActionPerformed

    private void fs10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fs10ActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font("Eras Bold ITC",Font.PLAIN,textArea.getFont().getSize()));
    }//GEN-LAST:event_fs10ActionPerformed

    private void fs11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fs11ActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font("Harlow Solid Italic",Font.PLAIN,textArea.getFont().getSize()));
    }//GEN-LAST:event_fs11ActionPerformed

    private void fs13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fs13ActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font("Times New Roman",Font.PLAIN,textArea.getFont().getSize()));
    }//GEN-LAST:event_fs13ActionPerformed

    private void fa14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fa14ActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font("Verdana",Font.PLAIN,textArea.getFont().getSize()));
    }//GEN-LAST:event_fa14ActionPerformed

    private void fs15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fs15ActionPerformed
        // TODO add your handling code here:
        textArea.setFont(new Font("Yu Mincho Demibold",Font.PLAIN,textArea.getFont().getSize()));
    }//GEN-LAST:event_fs15ActionPerformed

    private void redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redActionPerformed
        // TODO add your handling code here:
         

      
      
    
         textArea.setForeground(Color.RED);
    
    }//GEN-LAST:event_redActionPerformed

    private void blueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueActionPerformed
        // TODO add your handling code here:
         textArea.setForeground(Color.BLUE);
    }//GEN-LAST:event_blueActionPerformed

    private void blackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackActionPerformed
        // TODO add your handling code here:
         textArea.setForeground(Color.BLACK);
    }//GEN-LAST:event_blackActionPerformed

    private void yellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowActionPerformed
        // TODO add your handling code here:
         textArea.setForeground(Color.YELLOW);
    }//GEN-LAST:event_yellowActionPerformed

    private void greenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenActionPerformed
        // TODO add your handling code here:
         textArea.setForeground(Color.GREEN);
    }//GEN-LAST:event_greenActionPerformed

    private void orangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeActionPerformed
        // TODO add your handling code here:
         textArea.setForeground(Color.ORANGE);
    }//GEN-LAST:event_orangeActionPerformed

    private void pinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinkActionPerformed
        // TODO add your handling code here:
         textArea.setForeground(Color.PINK);
    }//GEN-LAST:event_pinkActionPerformed

    private void magentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_magentaActionPerformed
        // TODO add your handling code here:
         textArea.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_magentaActionPerformed

    private void cyanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cyanActionPerformed
        // TODO add your handling code here:
         textArea.setForeground(Color.CYAN);
    }//GEN-LAST:event_cyanActionPerformed

    private void grayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grayActionPerformed
        // TODO add your handling code here:
         textArea.setForeground(Color.GRAY);
    }//GEN-LAST:event_grayActionPerformed

    private void darkgrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkgrayActionPerformed
        // TODO add your handling code here:
        
         textArea.setForeground(Color.DARK_GRAY);
         
    }//GEN-LAST:event_darkgrayActionPerformed

    private void cutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutActionPerformed
        // TODO add your handling code here:
        textArea.cut();
    }//GEN-LAST:event_cutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextEditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextEditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextEditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextEditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TextEditorFrame().setVisible(true);
                } catch (BadLocationException ex) {
                    Logger.getLogger(TextEditorFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
  //  public static TextEditorFrame t ;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Asize12;
    private javax.swing.JMenuItem Asize16;
    private javax.swing.JMenuItem Asize20;
    private javax.swing.JMenuItem Asize24;
    private javax.swing.JMenuItem Asize36;
    private javax.swing.JMenuItem Asize40;
    private javax.swing.JMenuItem Asize48;
    private javax.swing.JMenuItem Asize54;
    private javax.swing.JMenuItem Asize60;
    private javax.swing.JButton Bold1;
    private javax.swing.JButton Italic;
    private javax.swing.JMenuItem black;
    private javax.swing.JMenuItem blue;
    private javax.swing.JButton copyButton;
    private javax.swing.JButton cut;
    private javax.swing.JMenuItem cyan;
    private javax.swing.JMenuItem darkgray;
    private javax.swing.JMenuItem fa14;
    private javax.swing.JMenuItem fs1;
    private javax.swing.JMenuItem fs10;
    private javax.swing.JMenuItem fs11;
    private javax.swing.JMenuItem fs13;
    private javax.swing.JMenuItem fs15;
    private javax.swing.JMenuItem fs2;
    private javax.swing.JMenuItem fs3;
    private javax.swing.JMenuItem fs4;
    private javax.swing.JMenuItem fs5;
    private javax.swing.JMenuItem fs6;
    private javax.swing.JMenuItem fs7;
    private javax.swing.JMenuItem fs8;
    private javax.swing.JMenuItem fs9;
    private javax.swing.JMenuItem gray;
    private javax.swing.JMenuItem green;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadButton;
    private javax.swing.JMenuItem magenta;
    private javax.swing.JButton newButton;
    private javax.swing.JMenuItem orange;
    private javax.swing.JButton pasteButton;
    private javax.swing.JMenuItem pink;
    private javax.swing.JButton quitButton;
    private javax.swing.JMenuItem red;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField statusField;
    private javax.swing.JTextArea textArea;
    private javax.swing.JMenuItem yellow;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
     
       
    
      
      }

    //private class SelectedText implements CaretListener {

        //@Override
       // public void caretUpdate(CaretEvent event) {
          //  int dot = event.getDot();
           // int mark = event.getMark();
            //if (dot != mark) {
               // if (dot < mark) {
                    //int temp = dot;
                    //dot = mark;
                    //mark = temp;
                //}
               // boldSelectedText(mark, dot);
            //}
       // }

       // private void boldSelectedText(int mark, int dot) {
       //     try {
                // try {
               // int length = dot - mark;
                //String s = textArea.getText(mark, length);
                // styledDocument.remove(mark, length);
               // styledDocument.insertString(mark, s,
                     // styledDocument.getStyle("bold"));
              // } catch (BadLocationException e) {
                  //e.printStackTrace();
            //} 
           // }
        //}
    }

    
   
